### ISSUE TITLE
Invalid example certificate

### ISSUE THREAD

**Issue by Craz1k0ek** [lapo-luchini/asn1js#43]
The example certificate is invalid, most importantly due to the fact that the length of one of the fields is 0x80 bytes long. Though valid BER, this is invalid DER as it suggests:

1. When the length is between 0 and 127, the short form of length must be used.
2. When the length is 128 or greater, the long form of length must be used, and the length must be encoded in the minimum number of octets.
3. For simple string types and implicitly tagged types derived from simple string types, the primitive, definite-length method must be employed.
4. For structured types, implicitly tagged types derived from structured types, and explicitly tagged types derived from anything, the constructed, definite-length method must be employed.

I suggest you update the example certificate to be valid DER and I would recommend having both a DER and BER example button to have the ability to show either of them.

**Comment by lapo-luchini** [comment]
[The example](https://lapo.it/asn1js/#MIAGCSqGSIb3DQEHAqCAMIACAQExCzAJBgUrDgMCGgUAMIAGCSqGSIb3DQEHAQAAoIAwggHvMIIBWKADAgECAhAvoXazbunwSfREtACZZhlFMA0GCSqGSIb3DQEBBQUAMAwxCjAIBgNVBAMMAWEwHhcNMDgxMDE1MTUwMzQxWhcNMDkxMDE1MTUwMzQxWjAMMQowCAYDVQQDDAFhMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCJUwlwhu5hR8X01f-vG0mKPRHsVRjpZNxSEmsmFPdDiD9kylE3ertTDf0gRkpIvWfNJ-eymuxoXF0Qgl5gXAVuSrjupGD6J-VapixJiwLXJHokmDihLs3zfGARz08O3qnO5ofBy0pRxq5isu_bAAcjoByZ1sI_g0iAuotC1UFObwIDAQABo1IwUDAOBgNVHQ8BAf8EBAMCBPAwHQYDVR0OBBYEFEIGXQB4h-04Z3y_n7Nv94-CqPitMB8GA1UdIwQYMBaAFEIGXQB4h-04Z3y_n7Nv94-CqPitMA0GCSqGSIb3DQEBBQUAA4GBAE0G7tAiaacJxvP3fhEj-yP9VDxL0omrRRAEaMXwWaBf_Ggk1T_u-8_CDAdjuGNCiF6ctooKc8u8KpnZJsGqnpGQ4n6L2KjTtRUDh-hija0eJRBFdirPQe2HAebQGFnmOk6Mn7KiQfBIsOzXim_bFqaBSbf06bLTQNwFouSO-jwOAAAxggElMIIBIQIBATAgMAwxCjAIBgNVBAMMAWECEC-hdrNu6fBJ9ES0AJlmGUUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTA4MTAxNTE1MDM0M1owIwYJKoZIhvcNAQkEMRYEFAAAAAAAAAAAAAAAAAAAAAAAAAAAMA0GCSqGSIb3DQEBAQUABIGAdB7ShyMGf5lVdZtvwKlnYLHMUqJWuBnFk7aQwHAmg3JnH6OcgId2F-xfg6twXm8hhUBkhHPlHGoWa5kQtN9n8rz3NorzvcM_1Xv9-0Eal7NYSn2Hb0C0DMj2XNIYH2C6CLIHkmy1egzUvzsomZPTkx5nGDWm-8WHCjWb9A6lyrMAAAAAAAA) is a PKCS#7 / CMS signature, not a certificate (though of course it contains the certificate that signed it in its structure, specifically at offset 50, and that part is entirely in DER form as mandated by [RFC5280](https://tools.ietf.org/html/rfc5280) section 4.1) and [RFC5652](https://tools.ietf.org/html/rfc5652) allows using BER in most of the structure:

> 2.  General Overview
> […] As a general design philosophy, each content type permits single pass processing using indefinite-length Basic Encoding Rules (BER) encoding.  Single-pass operation is especially helpful if content is large, stored on tapes, or is "piped" from another process.  […]  Signed attributes and authenticated attributes are the only data types used in the CMS that require DER encoding.

As far as I remember the example was generated using [Bouncy Castle](https://www.bouncycastle.org/java.html) (but I might be wrong about this) and as far as I can tell it is a perfectly valid CMS.

Yes, it is not entirely DER encoded (and given its small size I could have easily encoded in that form instead of using stream-based methods), but why should it be if the specs don't mandate for it? Also, I think that having a mix of BER and DER in a single example shows more features of the decoder.

Still, having more examples would be probably nice, and I'll probably add them with a drop-down menu.
(I'll close the issue after I have done that, but feel free to comment if you have any doubts regarding this)

**Comment by Craz1k0ek** [comment]
I was under the impression that it was a certificate, but your explanation of it being a CMS makes a lot of sense. And I too like the fancy feature of having the ability to decode a hybrid, that's cool! Only now I realised that there is a difference in the color of the length field, slightly different green for BER. 

With this new knowledge I would still:
1. Have both a BER and DER only example. I believe your website is a great tool for creating libraries and frameworks for ASN.1 and having non hybrid examples would be a great addition.
2. Describe what the example contains (I completely missed ~and failed to figure out myself~ that it was a CMS, it would be neat to have a description of the example. (I would also describe a BER/DER only example if/when you implement that)
3. Make more of a color difference for a BER length and DER length. It's hard to distinguish them.

**Comment by lapo-luchini** [comment]
I created a way to load external examples in 699d15aa67b26a6f5e6a9e31880c6f60e56fe708.
Will add some more.

**Comment by lapo-luchini** [comment]
With 2f303efe4474ebd23003662a323ed2f656f1961a I'd say this can be closed.
