### ISSUE TITLE
Where do you ingest the ASN specification files themselves to decode the bytestreams?

### ISSUE THREAD

**Issue by jkordani** [lapo-luchini/asn1js#48]
It is my understanding that you have to supply the ASN message definition somewhere in order to encode/decode the bytestreams.  Am I missing something?

Great library by the way

**Comment by lapo-luchini** [comment]
Hi! Thanks.

ASN.1 is a self-describing so you don't actually need definitions in order to encode/decode raw content.

Definitions are only used to describe/enforce specific formats, and also to give to values some property names.

BTW: in 0ccdbecd86e365ef7ab80328031206abf3c5be80 I started working on a specification parser in order to do that in the web interface too.

**Comment by jkordani** [comment]
Today I learned! Thanks!
