### ISSUE TITLE
Links do not preserve input format or encoding

### ISSUE THREAD

**Issue by schneidersoft** [lapo-luchini/asn1js#50]
After decoding some data the address bar contains a link with the ASN1 data encoded in base64.
When this link is loaded the input becomes the base64 form and the original input is lost.

example: when you decode PEM data with armoring the link should contain all the input data so that when the link is opened, the armoring/formatting/encoding of the input is preserved.

**Comment by lapo-luchini** [comment]
The current behavior is intentional: the URL contains the smallest possible data so that more fit into it, as URL are a [quite size-constrained](https://stackoverflow.com/a/417184/166524) medium already. Keeping original format such as PEM would need to store in the URL the base64 of data that has already been base64-encoded (PEM armoring is really just base64-encoding with a `-----BEGIN X-----` header/footer) and that would give a +33% overhead (over the already present +33% overhead).

**Comment by schneidersoft** [comment]
Sad. Makes sense though
