### ISSUE TITLE
Visual Studio Code integration

### ISSUE THREAD

**Issue by olibu** [lapo-luchini/asn1js#86]
Visual Studio Code is my preferred UI for development. But it lacks on in the visualisation of ASN1 files.

I'd like to have a WebView Plugin for VS Code to open files as they can be loaded in the browser.

Any further thoughts/ideas about this? 

@lapo-luchini : is this fine for you?

**Comment by lapo-luchini** [comment]
This is a wonderful idea!
I also like VSCode very much, and since it works with the same technology it should be too difficult to embed asn1js in a tab.

**Comment by lapo-luchini** [comment]
I've noticed the are two extensions already, but I didn't try them yet. Did you?

![image](https://github.com/lapo-luchini/asn1js/assets/420454/25f9f84b-623a-4e6b-9477-f4bda4ad19a1)

**Comment by olibu** [comment]
They both focus on syntax highlighting in ASN1 Editing. I did not found a method to decode base64 encoded binary data.
The second plugin additionally required .Net installed and a online backend which might be charged in future.

As I'm dealing more with x509 than with ASN1 Schemes both extensions doesn't fit.

Using a web view might be an quick and easy solution. Especially with the new ESM module it is not possible to start your HTML page locally. I prefer to keep my data private.
Alternatively an Electron App might be a solution.

However, as I'm missing an edit function I have my doubts, if a web view is really the right approach. Maybe a more complex Tree View with future edit functions might be a better approach. But I don't think that my available time would be sufficient and a first version would take much more time.

I may start with a quick and easy first version based on the esm branch.

**Comment by lapo-luchini** [comment]
I'd like to work on that too, but unfortunately I don't have the time to create my VSCode-extension-writing know-how so if you try that I'll (unfortunately!) will be mostly watching & appreciating.
To run the code locally instead of using ESM version as is, you con package it with vite/webpack/esbuild and the resulting code should work correctly locally as well.
But maybe in the VSCode context there are better ways to do it, I don't know (yet).

**Comment by lapo-luchini** [comment]
OK, contrary to what I said, curiosity was too much and I'm trying it myself as I have a couple of spare hours. 🤣
(I'm using a local monotone repository, will mirror it on github when I have something at least minimal to show…)

**Comment by lapo-luchini** [comment]
Pretty neat! 😎
![image](https://github.com/lapo-luchini/asn1js/assets/420454/844fa118-97bc-408d-a127-9be83edd7322)

**Comment by lapo-luchini** [comment]
[GitHub mirror](https://github.com/lapo-luchini/vscode-asn1js).

**Comment by lapo-luchini** [comment]
I also added some rough [documentation to install it](https://github.com/lapo-luchini/vscode-asn1js?tab=readme-ov-file#developer-installation).

Everything is very much work in progress and with rough edges (e.g. it doesn't use the dark theme, and I disabled hex dump as it was too cumbersome in a small window), but I have no more time today, so feel free to hack at it or whatever you prefer!

**Comment by olibu** [comment]
That looks great!
I started with something similar. But faced some security javascript
issues.
I found some dark mode details already.

Regarding the hex view, I recognized some issues on mobile phones, too.

Maybe a switch button would be an option.

**Comment by lapo-luchini** [comment]
I [fixed dark mode](https://github.com/lapo-luchini/vscode-asn1js/commit/29505142c837ed714567d185de7da9934b3a992f) too.
Now that the project exists, I'd say this issue is no longer needed here.
If you have any suggestion/idea/patch for the extension open one [directly there](https://github.com/lapo-luchini/vscode-asn1js/issues), thanks!
